version: "3.0"

services:
  node:
    image: node:latest
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: bash -c "npm install && npm run dev"
    tty: true
    